### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by rivatove** [MrLoh/eslint-plugin-no-catch-all#1]
Just wanted to show my appreciation. This was a common source of bugs for me and I was writing unit tests to ensure that errors are bubbled. Surprised this plugin isn't more popular, it's crucial for me!

Thank you.

**Comment by MrLoh** [comment]
Great to hear. Let me know if there is functionality missing. Error hygiene is an under valued area in many programming languages I think.

**Comment by rivatove** [comment]
> Great to hear. Let me know if there is functionality missing. Error hygiene is an under valued area in many programming languages I think.

Hi @MrLoh, I think it could be cool to port the functionality to Promise catch method as well if you ever have time for that.
